[package]
name = "invoicer"
version = "0.1.0"
edition = "2021"
authors = ["Michael Winkelmann (michael@winkelmann.site)"]
keywords = ["work","time","accounting","shell"]


[dependencies]
clap = { version = "4.1", features = ["derive","cargo"] }
toml = "0.8.6"
csv = "1.3.0"
