
[contact]
fullname = "John Doe"
street = "123 Fake St."
zipcode = 1234
email = "john@doe.com"
city = "Berlin"
country = "Germany"
phone = "+49123456789"

[payment]
accountholder = "John Doe"
iban = "DE123456789012345678"
bic = "MYBANKID"
taxid = "12345678"
currency = "EUR"
taxrate = 19.0

[invoice]
template = "invoice.tex"
number_format = "%Y%m%"
filename_format = "INVOICENUMBER_$INVOICE_$INVOICEE.tex"
days_for_payment = 14
calculate_value_added_tax = true
timesheet = true