
[contact]
fullname = "John Doe"
street = "123 Fake St."
zipcode = 1234
email = "john@doe.com"
city = "Berlin"
country = "Germany"
phone = "+49123456789"

[payment]
accountholder = "John Doe"
iban = "DE123456789012345678"
bic = "MYBANKID"
taxid = "12345678"
tax_rate = 19.0
default_rate = 100.0

[invoice]
template = "invoice.tex"
number_format = "%Y%m${COUNTER}"
filename_format = "${INVOICENUMBER}_${INVOICE}_${INVOICEE}.tex"
days_for_payment = 14
calculate_value_added_tax = true
timesheet = true