[directories]
config = "${WORKING_DIR}"
tags = "${CONFIG_DIR}/tags"
templates = "${CONFIG_DIR}/templates"
invoices = "${HOME}/Documents/invoices/${YEAR}"

[contact]
fullname = "John Doe"
street = "123 Fake St."
zipcode = 1234
email = "john@doe.com"
city = "Berlin"
country = "Germany"
phone = "+49123456789"

[payment]
accountholder = "John Doe"
iban = "DE123456789012345678"
bic = "MYBANKID"
taxid = "12345678"
tax_rate = 19.0
default_rate = 100.0

[invoice]
template = "invoice.tex"
timesheet_template = "timesheet.tex"
number_format = "%Y%m${COUNTER}"
date_format = "%Y/%m/%d"
filename_format = "${INVOICENUMBER}_${INVOICE}_${RECIPIENT}.tex"
days_for_payment = 14
calculate_value_added_tax = true
output_folder = ""

